### ISSUE TITLE
Misaligned table-cells

### ISSUE THREAD

**Issue by narcolepticinsomniac** [Tampermonkey/tampermonkey-layout#1]
@derjanb The update you pushed recently messed up the alignment. Not as noticeable with light borders, so I made them black for emphasis:

![tm-borders](https://user-images.githubusercontent.com/14100003/32639502-4348f8d0-c592-11e7-9cf1-b8727fe6b746.png)

The culprit is:

```
.icon16 {
    width: 1.3em;
    height: 1.3em;
}
```

As a result, all `td` with icons are off by a hair, causing many jagged breaks in the border across the whole row. Both measurements should be `16px`, as the element name implies.

**Comment by narcolepticinsomniac** [comment]
When I went back in TM, I noticed that `.icon16` images aren't vertically centered. This is true regardless of their sizing. Instead of resizing them, I left them at `1.3em` and adjusted parent elements to fix vertical and border alignment. Good enough for me, so maybe you'll find it useful:

```
/* 1px black borders to gauge vertical alignment easier */
.scripttable tr {
    border: 1px solid #000!important;
}

/* Overrides for code you could eliminate */
.nameNname16 {
    top: 0!important;
}
.nameNicon16 {
    margin-top: 0!important;
}

/* Vertical alignment */
.settingstd > :not([style="display: none;"]):not(.script_type):not(.slider-frame),
.settingstd a[target="_blank"] {
    display: inline-flex!important;
    vertical-align: middle!important;
}
.scripttable td,
.scripttable th {
    padding: 5px!important;
}
```

**Comment by narcolepticinsomniac** [comment]
Also found a bug. Figured I may have created it with some crap CSS, but I can repro in a clean profile. Toggling scripts in the manager removes all content from the entire "Features" column. Made a screen record: [TM-toggle bug.zip](https://github.com/Tampermonkey/tampermonkey-layout/files/1460219/TM-toggle.bug.zip)

**Comment by derjanb** [comment]
> The update you pushed recently messed up the alignment.

I checked this and the problem is also present at 4.4 if using a recent Chrome version, but not at older versions. I used 43.0.2321.0 for a quick test. So I guess Chrome now calculates the height a little bit different. 🤔

> Toggling scripts in the manager removes all content from the entire "Features" column. 

I've addressed both issues in [version 4.5.5597](http://tampermonkey.net/changelog.php?version=4.5.5597&ext=gcal). Thanks for reporting

> When I went back in TM, I noticed that .icon16 images aren't vertically centered.

That's the only remaining issue. I have no idea at the moment, why vertical alignment doesn't work here, while it's working fine at the tables of the action menu. I need to do some further investigation...

**Comment by narcolepticinsomniac** [comment]
Yeah, I hate `table` layouts, plus the selectors usually suck, as they kinda do here. For easily aligning content `flex` is way easier, but converting might be a huge PITA depending on the js. Basically they're not aligning because their parent elements don't have `display` set. I'm in the business of short and sweet hacky CSS solutions like the one above, which works, but I can see why you may be reluctant to use it.

This is something along the lines of a proper solution (minus the `!important` declarations when implemented directly):

```
.script_name > span,
.settingstd:nth-of-type(8) > span,
.script_name > span,
.settingstd:nth-of-type(9) > span,
.script_name > span,
.settingstd:nth-of-type(10) > span,
.script_name > span,
.settingstd:nth-of-type(10) > span > a,
.script_name > span,
.settingstd:nth-of-type(11) > span,
.script_name > span,
.settingstd:last-of-type > span {
    display: inline-block!important;
}
.settingstd > input[type="checkbox"],
.settingstd:nth-of-type(2) > span,
.settingstd:nth-of-type(5) > span,
.icon16 {
    vertical-align: middle!important;
}

/* Deletable overrides */
.script_name > span > .nameNicon16 {
    margin-top: 0!important;
    vertical-align: text-bottom!important;
}

.script_name > span > .nameNname16 {
    top: 0!important;
}

/* .scripttable tr were different heights. Those containing .nameNicon16 were 36px, the rest were 33px. Since everything is vertically aligned, we can lose padding and specify height. Readjust the padding if you prefer, but odd numbers are tricky and I kinda like 33px. */
.scripttable td,
.scripttable th {
    padding: 0!important;
    height: 28px!important;
}
```

Aligned the numbers as well. Tiny difference, but might as well.

**Comment by narcolepticinsomniac** [comment]
Edit: 28px height achieves 33px. Some funky `table-cell` black magic f*ckery still adds some pseudo-padding. It's the height I wanted, so I'm not investigating.

Edit 1 1/2: Not black magic. Originally tested with my dark style which has 1px borders with box-shadow, whereas yours now have 5px. 28 + 5 = 33. If you decide to use height over padding, the dark style needs:

```
.scripttable td,
.scripttable th {
    padding: 0!important;
    height: 32px!important;
}
```
If you use padding, it'd also need more.

Edit2: `.nameNicon16 {vertical-align: text-bottom!important;}`

Edit3: I am done screwing with this. Hopefully some of it's useful.

**Comment by narcolepticinsomniac** [comment]
Redesign fixes the layout.
