### ISSUE TITLE
Enabled/disabled toggles are backwards

### ISSUE THREAD

**Issue by narcolepticinsomniac** [Tampermonkey/tampermonkey-layout#2]
I've done the same type of thing with the FontAwesome toggles before. The "off" toggle sucks, so you use the "on" for both, and change the direction for "off". You have the directions backwards though, "on" should be to the right, and "off" to the left:

![toggles](https://user-images.githubusercontent.com/14100003/33225529-45f989c6-d147-11e7-8253-cd4157f326db.png)

I'd also suggest using `matrix` instead of just `rotate`. I see no real issues with it here, but have noticed tiny positional issues in the past using `rotate`, where `matrix` worked perfectly. Also, if you wanna give the toggle buttons a little color, you can throw another pseudo under them. The default also needs a dummy transform to make the underlying pseudo visible. Probably other ways with `backface-visibilty` or something, but NBD either way.

Example you can paste in user CSS to check out:

```
.enabler i {
    position: relative!important;
}
.enabler i:after {
    content: ''!important;
    height: 11px!important;
    width: 18px!important;
    position: absolute!important;
    border-radius: 6px!important;
    z-index: -1;
}
.enabler i.on:after {
    left: 1px;
    top: 3px;
    background: hsl(88, 60%, 72%)!important;
}
.enabler i.off:after {
    right: 1px;
    bottom: 3px;
    background: hsl(0, 0%, 86%)!important;
}
.enabler i.on {
    transform: matrix(1, 0, 0, -1, 0, 0)!important;
    color: hsl(88, 60%, 30%)!important;
}
.enabler i.off {
    transform: matrix(-1, 0, 0, 1, 0, 0)!important;
    color: hsl(0, 0%, 40%)!important;
}
.actiontable .enabler .far {
    margin: 0 6px!important;
    font-size: 15px!important;
    min-width: unset!important;
}
.actiontable .enabler i:after {
    height: 9px!important;
    width: 15px!important;
}
```

Edit: fixed toggle backdrop positions.

Edit2: Noticed the popup toggles move up 1px when disabling. This can be fixed by tweaking the font size. 15px looked about right. 

Really, what needs fixing is the directions and that 1px jump, but I realigned the pseudo backdrops so they're good.

**Comment by derjanb** [comment]
> You have the directions backwards though

In fact this was intentional, because it fits to TM's old sliders. However, after some investigation I noticed, that FontAwesome, Android and even Microsoft are doing it wrong. That's why I'll change TM to do it wrong as well. 😁

> where matrix worked perfectly

Of course mirroring should be more accurate.

**Comment by derjanb** [comment]
Fixed. :) Thanks for these suggestions.
