### ISSUE TITLE
Close tab icon garbled

### ISSUE THREAD

**Issue by narcolepticinsomniac** [Tampermonkey/tampermonkey-layout#3]
Not sure if it's on your end, or if it's a case of not having a compatible font installed. You're including FontAwesome and using an "X" icon successfully elsewhere, so there should be no font issues. Either way, this is what I get:

```
.tv_tab_close:before {
    content: "Ã—";
}
```

**Comment by derjanb** [comment]
Unfortunately the FontAwesome equivalent to × and ● do have some offset to each other so that the icon would wobble.

What TM version? 4.5.5660? Firefox or Chrome? Windows 10?

Edit: I've replaced ⚫ (\u26AB) with ● (\u25CF) at the latest Safari version, because it was much too large there. So maybe this issue will be fixed at the next beta anyway.

**Comment by narcolepticinsomniac** [comment]
Safe to assume I'm always on the latest beta in the Chrome Web Store. I use Cent browser so it lags a couple weeks behind. It's currently Chromium 62.0.3202.94. Win 8. OS shouldn't matter since you're loading the font though.

Guess I wasn't clear. I'm not talking about some minor inconsistency, FontAwesome is failing for those symbols altogether. Testing again, I can see that they don't fail every time, although it happens fairly frequently. Haven't pinpointed an exact scenario to repro consistently. It's falling back to the same gibberish characters you get if you specify a unicode that the OS doesn't support:

![font](https://user-images.githubusercontent.com/14100003/34197157-30a51b26-e533-11e7-9242-82b8a31ffe2b.png)

**Comment by narcolepticinsomniac** [comment]
Finally figured it out. Bug is caused by devtools being open, somehow or another. I made a screen record. I assumed you were using FontAwesome there as well, but it looks like you're using a text symbol. Seems slightly different than a typical "x" anyway. I've been surprised a few times with reports of "web-safe" characters having all types of weird inconsistencies. Issues with devtools is a new one though.

[font-bug.zip](https://github.com/Tampermonkey/tampermonkey-layout/files/1575088/font-bug.zip)

**Comment by derjanb** [comment]
Seems to be fixed at Chrome 65.0.3325.18.

**Comment by narcolepticinsomniac** [comment]
Yeah man, this isn't specific to TM. I meant to close this shortly after, when I noticed it elsewhere. Good to know it's fixed in future versions of Chromium though.
