### ISSUE TITLE
CSS Update

### ISSUE THREAD

**Issue by narcolepticinsomniac** [Tampermonkey/tampermonkey-layout#4]
Hey @derjanb, I updated my personal style using the code here as a base. Fixed a lot of bugs and improved a bunch of stuff, including custom checkboxes, selects, and better buttons. Added some nicer horizontal gradient hovers for clickable `tr` in the popup and editor dropdowns. Their data-images are kinda big, but compressing them ruins the quality/effect. Suppose you could convert to png if that matters, but I think they look a lot nicer.

Tested in Chromium, Firefox, Opera, and Vivaldi. You can test it as user CSS with the default light theme.

Chrome started doing that weird popup outline a few versions back, but I can't really fix that without affecting forks which didn't adopt the same weird behavior. In Stylus, we added an option to add back white borders to the sides, so they're not just on the top and bottom. It'd be nice if TM did the same, but NBD I guess.

My CodeMirror theme is at the bottom in case you feel like incorporating it somehow this time. As it is, it styles the default editor theme. Never really tested with others.

**Comment by narcolepticinsomniac** [comment]
Oh btw, one of the bugs fixed wasn't theme related, as it was present in the default. 

On the scripts page, the search bar becomes a sticky header when the page is scrolled, but the close button position isn't accounted for. It winds up under the input IIRC.

**Comment by narcolepticinsomniac** [comment]
Actually, in testing I find that FF has a slight speed glitch with initial hover data-images, because they're determined to defy all logic. Converting them all to png would likely be beneficial, and since they're essentially cached, it shouldn't have any negative effect otherwise.

**Comment by narcolepticinsomniac** [comment]
Alright, might as well continue this conversation with myself. I took a few more liberties in terms of changing the `display` of elements in the popup in this next version, but it mimics the original layout. The objective was to alter the active enabled/disabled script list in the popup so that each `tr` was entirely clickable, and give them the same snazzy transparent horizontal gradient as other clickable `tr`. 

There's some slightly hacky CSS involved, but I really like the look of it and the improved functionality as far as larger clickable areas. This is what I'm gonna use personally, so I figured you might also wanna check it out.

https://pastebin.com/PcgYsMX4

**Comment by derjanb** [comment]
Yes, this looks good. I'll check and incorporate the changes as soon as possible. Thanks for working on this. :)

**Comment by narcolepticinsomniac** [comment]
Updated link with a bug fix. I'll continue to do that if I come across any issues, so whenever you get around to messing around with this, make sure you grab the updated code.

**Comment by narcolepticinsomniac** [comment]
Switched to the one better version. Updating two was a PITA. Updated for new popup selectors `.script_context_menu` and `.context_entry`. Left the old ones for compatibility. 

Allowing script names to cause overflow in the popup, as they can in the default, is not the best UX. Popup max-width is 800px, and we know the width of the rest of the layout, so setting a more appropriate max-width with ellipsis will account for edge cases better:

Default theme
```
.actionpostr > .actionpostd:nth-of-type(2) .actiontable > tr > td:nth-child(2) {
    max-width: 480px!important;
}
.actionpostr > .actionpostd:nth-of-type(2) .actiontable > tr > td:nth-child(2) > div {
    overflow: hidden!important;
}
.actionpostr > .actionpostd:nth-of-type(2) .actiontable > tr > td:nth-child(2) > div > div {
    overflow: hidden!important;
    text-overflow: ellipsis!important;
}
```

Before:

![tm overflow](https://user-images.githubusercontent.com/14100003/37562318-b05d0ade-2a3b-11e8-8545-a57daddd5d90.png)


After:

![tm ellipsis](https://user-images.githubusercontent.com/14100003/37562322-bbc0494a-2a3b-11e8-8dae-7d23c8020fc4.png)

**Comment by narcolepticinsomniac** [comment]
Accounted for new selector for disabled script name text color in the popup. Probably better that it only switches once it's not actually active anymore.

Excluded FF ESR from custom checkboxes since `-moz-appearance: none;` is bugged in it.

**Comment by narcolepticinsomniac** [comment]
@derjanb Pretty big oversight on my part. I was playing around with matching subtle zebra-striping for scripts in the popup, and a friend that was testing said they weren't working. Apparently, not only are there options for 1, 2, or 3 columns which I didn't account for, but at some point I switched them to 2 from the default and forgot the option even existed.

Unless you were testing with 2 columns, we probably haven't been seeing the same thing. Anyway, I accounted for any number of columns now and added subtle zebra-striping in the popup script list(s). Probably a few other tweaks.

https://pastebin.com/cwnHbgwF

**Comment by derjanb** [comment]
@narcolepticinsomniac I've just tested the latest paste and I found that the action menu font size is very small even though it's set to 85% as always. Do you see the same? Setting it to 100% fixes the issue, but I'm not sure, why the new styles make a difference here.

![image](https://user-images.githubusercontent.com/767504/37989777-a668a7f6-3204-11e8-9f7a-687a4dfbc8cb.png)

**Comment by narcolepticinsomniac** [comment]
Hmm. Pretty sure I didn't change any font sizes except for buttons, and they should pretty much be the same as the defaults. Only thing about the size that may have changed is that I've offset zoom in the popup for common zoom levels, 110%, 125%, and 150%. 

Chromium zooms the popup if you zoom any of the other extension pages, like the script manager. Other browsers don't because it's pretty stupid, but it seems intended in Chromium. The popup layout isn't conducive to overflow at higher zoom levels, and since it's only in Chromium, I offset it with a counter-`zoom:`. 

That's just a guess if things look a bit smaller. These screens could also kick in due to OS DPI settings.

**Comment by narcolepticinsomniac** [comment]
I'm curious if it was the DPI media-screens causing the issue. I think they're a good idea. Regardless, you can always tweak details to your liking. I'd maintain this theme for my own personal use anyway, because I prefer it much more than the default. The only real extra work I'm doing is testing for both stable/beta, and trying to account for all possible options and settings I would never encounter personally. Worthwhile if some users like it.

I neglected to test popup script name max-width/ellipsis in stable, and `.script_name` doesn't exist yet in stable, so I set the max on the parent and accounted for both stable/beta. Should be good in either, and hopefully that's one of the last discrepancies. 

https://pastebin.com/swS20mnM (updated)

**Comment by narcolepticinsomniac** [comment]
The Codemirror CSS shouldn't really be incorporated as-is since it overrides all optional themes, but I think it'd be fine if it only affected the default. With that in mind, I switched all the CM code to use the `.cm-s-default` parent selector. That way, the default dark theme only affects the default CM theme.

https://pastebin.com/c4NtrGMY

**Comment by narcolepticinsomniac** [comment]
Couple minor tweaks: https://pastebin.com/ncj1kUtK

On an unrelated note, since the latest beta update today, all my jQuery scripts show warnings for `'$' is not defined` everywhere.

**Comment by narcolepticinsomniac** [comment]
Style CM diff since it's not included by `.cm-s-default`: https://pastebin.com/EqueegZ2

**Comment by derjanb** [comment]
FYI: I'm sorry, I'm pretty busy with incorporating GDPR. I'll continue to integrate the new layout as soon as possible.

**Comment by narcolepticinsomniac** [comment]
NBD. It's given me a chance to work the kinks out. I think the last one is pretty damn complete whenever you get around to it.

**Comment by narcolepticinsomniac** [comment]
Styled `.editorbuttonbar` buttons, and CM auto-suggest.

https://pastebin.com/fppk32XR

**Comment by narcolepticinsomniac** [comment]
@derjanb It's been a few months since I posted the first draft, and quite a while since the last. I get that this isn't a priority, but the update is far less buggy and far more complete. 

If there's some other reason you're putting this off, something you don't like, just let me know. Otherwise, I'm not sure why a simple theme update is getting back-burnered for months.

**Comment by derjanb** [comment]
@narcolepticinsomniac I was quite busy because my second child was born these days, GDPR became effective, 4.6 needed to released... I'll work on this as soon as possible. 😃

**Comment by narcolepticinsomniac** [comment]
Congrats! Sleep is overrated. =)

Makes the delay seem much more reasonable. Hopefully you can get to it soon.

**Comment by derjanb** [comment]
Fixed via f88aee6da9f96a0f21c67e62f423e1058843e134

I had to remove some zoom statements because they caused the action menu to be very small. Can you please check?
![image](https://user-images.githubusercontent.com/767504/41345987-7de44e5a-6f05-11e8-9501-b8689400a36f.png)

I also tuned the theme here and there and created a 'default-dark' editor theme which is choosen by default if the layout is switched to dark and no editor theme was saved manually: https://github.com/Tampermonkey/tampermonkey-layout/compare/fppk32XR...master

**Comment by narcolepticinsomniac** [comment]
Chromium applies any manager zooms to popups, whereas FF doesn't. I'm curious how things would be smaller in an unintentional way. Is the behavior different in different forks or OS? Those screens could also kick in with system DPI.

The idea is that zoom is applied to counteract detected pixel size. e.g. 110% browser zoom = `zoom: .9;` Chrome also erroneously applies zoom to custom scrollbars, so I've been resizing them for 110%, 125%, and 150% for a while now. Actually just rewrote it a few days ago to also resize with zoom instead of unit measurements. Now they include every 5% step in between, which are available in Cent Browser. 

You kinda need to do something in the popup if you want to account for edge cases with zoom and text-overflow/ellipsis in the popup. Either counteract the zoom, or shorter `max-widths` at higher zoom levels, or there can be overflow in the main popup. 

Maybe people who screw with zoom, get what they get, but I tried to be thorough. It's all your call ultimately. I could actually update it to include all 5% steps from 100%-150%, or you can scrap it altogether. 

Otherwise, yeah, all seems fine.

**Comment by narcolepticinsomniac** [comment]
Update for every 5% step from 100%-150% for zoom offset on custom scrollbars and the Chromium popup, in case you want it (minus CM): https://pastebin.com/j6GB2cjJ

IDK man, I tested in Vivaldi, which doesn't have the stupid popup zoom bug/feature, and if pixels are normal size, they're ignored. If they're bigger, they're offset back to normal. Bear in mind, if you're inspecting unit measurements, you gotta inspect the element the zoom is actually on, because it'll do funny things to parent/child pixel units displayed. You can also eyeball it by which bookmark it hits. Zoom offsets keep the whole popup size consistent within a few pixels.

Only way I can think that something might be smaller than expected, is if you're used to it being bigger with a custom system DPI setting. I thought it was a clever solution, but I guess I could be wrong for whatever reason. Like I said, delete it if you really think it's buggy. I just wanted you to have the more complete version In case you see it working right now.
