### ISSUE TITLE
`Trash` tab content is unstyled in `Default - Dark` and `Default - Darker` themes

### ISSUE THREAD

**Issue by darkred** [Tampermonkey/tampermonkey-layout#6]
I've noticed that the `Trash` tab content is unstyled in `Default - Dark` and `Default - Darker` themes.
Here are screenshots with a fresh Chrome 88 profile with TM (beta 4.12.6126) in win 10:

<details>
<summary>Default - Dark</summary>

![2021-01-27_000736](https://user-images.githubusercontent.com/723651/105912206-c8006600-6033-11eb-809c-ea12a6665957.jpg)
</details>

<details>
<summary>Default - Darker</summary>

![2021-01-27_000757](https://user-images.githubusercontent.com/723651/105912210-c9319300-6033-11eb-9203-1459e6d41fb8.jpg)
</details>

Kindly cc'ing @narcolepticinsomniac 

Thank you

**Comment by narcolepticinsomniac** [comment]
I only maintain the darker theme. Should be good now whenever @derjanb grabs the updated CSS. In the meantime, you could fix it via user CSS:

```
.darker dt,
.darker dd {
  color: hsl(0, 0%, 66%)!important;
}

.darker .trash_script_details,
.darker .trash_actions {
  background-color: hsl(0, 0%, 18%)!important;
  border: 1px solid #000!important;
  box-shadow: inset 0 0 0 1px hsl(0, 0%, 24%), 0 0 0 1px hsl(0, 0%, 24%)!important;
}

.darker .tv_tab[tvid="trash"] > div {
  font-size: 0!important;
}

.darker .tv_tab[tvid="trash"] > div:before {
  content: '\f2ed'!important;
  font-family: 'Font Awesome 5 Regular'!important;
  font-weight: 400!important;
  font-size: 16px!important;
}

.darker .was_deleted .script_name {
  padding-left: 36px!important;
}

.darker .was_deleted {
  pointer-events: none!important;
}
```

**Comment by darkred** [comment]
Thanks a lot for the quick response!

**Comment by narcolepticinsomniac** [comment]
Sure thing. I edited that CSS a few times after I originally commented. Make sure you got the one minus the typos. =)
